version: "3.7"

services:
  nginx:
    image: nginx:1.17-alpine
    volumes:
      - /etc/stikked/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./htdocs:/htdocs:ro
      - /etc/ssl/private/txt.lolicon.eu.key:/etc/ssl/private/txt.lolicon.eu.key:ro
      - /etc/ssl/private/txt.lolicon.eu.pem:/etc/ssl/private/txt.lolicon.eu.pem:ro
      - /etc/stikked/dhparam.pem:/etc/ssl/private/dhparam.pem:ro
    ports:
      - "7001:443/tcp"
    restart: always
    depends_on:
      - php
      - mysql

  php:
    image: stikked-php:1
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./htdocs:/htdocs
      - /etc/stikked/stikked.php:/htdocs/application/config/stikked.php:ro
    build:
      context: ./docker/php
    restart: always

  mysql:
    image: mariadb:10.4
    command: mysqld --innodb-buffer-pool-size=4000000000
    volumes:
      - stikked-sql:/var/lib/mysql
    env_file: /etc/stikked/stikked-sql.env
    restart: always

networks:
 stickkednet:

volumes:
  stikked-sql:
